FROM golang:1.26-alpine AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 go build -trimpath -o /bin/meowsight-proxy ./cmd/meowsight-proxy

FROM scratch
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=builder /bin/meowsight-proxy /meowsight-proxy
COPY --from=builder /app/configs /configs
EXPOSE 8081
ENTRYPOINT ["/meowsight-proxy"]
